phobos_share:
    config:
        path: '{path}'
        requirements: { path: '^(?!(fr/|nl/|de/|_wdt/|_profiler/|file/)(.*$)?).*' }
        host: share.myam.dk
        controller: 'emsch.controller.router::redirect'
    template_static: template/redirect/phobos.json.twig
blog_test_print_margin:
    config:
        path: /blog/test/page-margin-print-css
    template_static: template/blog/page-margin-print-css.html.twig
google-site-verification:
    config:
        path: /google559a317bdba2ec40.html
    template_static: template/seo/google-site-verification.html.twig
robots.txt:
    config:
        path: /robots.txt
        defaults: { _format: txt }
    template_static: template/seo/robots.txt.twig
favicon_ico:
    config:
        path: /favicon.ico
        controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction'
        defaults: { permanent: true, path: '/bundles/emsch_assets/static/icon64.png?1b0ece819cfd009e2a86eb0fb007dc2df2c766b8' }
match_all_pdf:
    config:
        path: { fr: 'fr/{path}.pdf', en: '{path}.pdf' }
        controller: 'emsch.controller.router::asset'
        defaults: { path: / }
        requirements: { path: '^(?!(_wdt|_profiler|file)(\/.*$)?).+' }
    query: '{"query":{"bool":{"must":[{"term":{"path":{"value":"%path%","boost":1}}},{"term":{"locale":{"value":"%_locale%","boost":1}}},{"terms":{"_contenttype":["page"]}}]}},"size":1}'
    template_static: template/pages/page.pdf.twig
match_all:
    config:
        path: { fr: 'fr/{path}', en: '{path}' }
        defaults: { path: / }
        requirements: { path: '^(?!(_wdt|_profiler|_error|file)(\/.*$)?).+' }
    query: '{"query":{"bool":{"must":[{"term":{"path":{"value":"%path%","boost":1}}},{"term":{"locale":{"value":"%_locale%","boost":1}}},{"terms":{"_contenttype":["page"]}}]}},"size":1}'
    template_static: template/pages/page.html.twig
emsch_error:
    config:
        path: '/_error/{statusCode}'
        controller: 'emsch.controller.router::errorPreview'
        defaults: { statusCode: 500 }
